In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v1", is_slippery=False)

In [3]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n
q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
num_episodes=10000 #that we want an agent to play during the training 
max_steps_per_episode=100 # max number of stept that the agent take in one single episodes

learning_rate=0.1 
discount_rate=0.99 

exploration_rate=1 #epsilon gredy 
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.001

In [22]:
import numpy as np
import random

reward_all_episodes = []

# Q-learning
for episode in range(num_episodes):  
    state = env.reset()[0]  
    done = False
    reward_current_episode = 0

    for step in range(max_steps_per_episode):  
        # Exploration-Exploitation 
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])  # Exploitation
        else:
            action = env.action_space.sample()  # Exploration

        new_state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated  

        # Update the Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
                                 learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        reward_current_episode += reward
        
        if done:
            break

    # minimise exploration rate
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    reward_all_episodes.append(reward_current_episode)


rewards_per_thousand_episodes = np.array_split(np.array(reward_all_episodes), num_episodes // 1000)
count = 1000
print(" Average reward per thousand episodes \n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r) / 1000))
    count += 1000

print("\n\n******** Q-table ********\n") 
print(q_table)

 Average reward per thousand episodes 

1000 :  0.291
2000 :  0.725
3000 :  0.886
4000 :  0.961
5000 :  0.971
6000 :  0.986
7000 :  0.991
8000 :  0.986
9000 :  0.995
10000 :  0.99


******** Q-table ********

[[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.95099005 0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]


In [10]:
import time
from IPython.display import clear_output

print("\n\n Testing the trained agent \n")
for episode in range(5):  
    state = env.reset()[0]
    done = False
    print("Episode", episode + 1)
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(q_table[state, :])  
        new_state, reward, terminated, truncated, info = env.step(action)

        terminated = bool(terminated)
        truncated = bool(truncated)    
        
        done = terminated or truncated  

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print(" You winl  ")
            else:
                print(" You Lose ")
            time.sleep(3)
            clear_output(wait=True)
            break

        state = new_state

env.close()

 You reached the goal! 
